package app.bpartners.geojobs.service.threed.model;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import lombok.SneakyThrows;

/**
 * Roof slope and height read from a LOD2 CityJSON generated by threed.
 *
 * <p>The slope is the one of the largest roof surface. The height is the highest roof vertex minus
 * the mean of the ground vertices.
 */
public record CityJsonRoofMetrics(boolean hasRoof, double slopeInDegrees, double heightInMeters) {
  private static final String ROOF_SURFACE = "RoofSurface";
  private static final String GROUND_SURFACE = "GroundSurface";
  private static final String SLOPE_KEY = "slope_in_degrees";
  private static final String AREA_KEY = "area_in_square_meters";

  @SneakyThrows
  public static CityJsonRoofMetrics from(File cityJson) {
    return from(new ObjectMapper().readTree(cityJson));
  }

  public static CityJsonRoofMetrics from(JsonNode cityJson) {
    var vertices = toVertices(cityJson);
    var roofZs = new ArrayList<Double>();
    var groundZs = new ArrayList<Double>();
    var largestRoofArea = -1.0;
    var slope = 0.0;

    for (var cityObject : cityJson.path("CityObjects")) {
      for (var geometry : cityObject.path("geometry")) {
        var semanticSurfaces = geometry.path("semantics").path("surfaces");
        var surfaces = new ArrayList<JsonNode>();
        var values = new ArrayList<JsonNode>();
        flattenSurfaces(
            geometry.path("boundaries"),
            geometry.path("semantics").path("values"),
            depthToSurface(geometry.path("type").asText()),
            surfaces,
            values);

        for (int i = 0; i < surfaces.size(); i++) {
          var value = values.get(i);
          if (value == null || !value.isInt()) continue;
          var semantic = semanticSurfaces.path(value.asInt());
          var type = semantic.path("type").asText();
          if (ROOF_SURFACE.equals(type)) {
            addZs(surfaces.get(i), vertices, roofZs);
            var area = semantic.path(AREA_KEY).asDouble(0);
            if (area > largestRoofArea) {
              largestRoofArea = area;
              slope = semantic.path(SLOPE_KEY).asDouble(0);
            }
          } else if (GROUND_SURFACE.equals(type)) {
            addZs(surfaces.get(i), vertices, groundZs);
          }
        }
      }
    }

    if (roofZs.isEmpty()) {
      return new CityJsonRoofMetrics(false, 0, 0);
    }
    var maxRoofZ = roofZs.stream().mapToDouble(Double::doubleValue).max().orElse(0);
    var meanGroundZ = groundZs.stream().mapToDouble(Double::doubleValue).average().orElse(maxRoofZ);
    return new CityJsonRoofMetrics(true, slope, ceil2(maxRoofZ - meanGroundZ));
  }

  /** Number of array levels above a surface in the boundaries of the given geometry type. */
  private static int depthToSurface(String geometryType) {
    return switch (geometryType) {
      case "Solid" -> 1;
      case "MultiSolid", "CompositeSolid" -> 2;
      default -> 0;
    };
  }

  private static void flattenSurfaces(
      JsonNode boundaries,
      JsonNode values,
      int depth,
      List<JsonNode> surfaces,
      List<JsonNode> flatValues) {
    for (int i = 0; i < boundaries.size(); i++) {
      var value = values.isArray() ? values.get(i) : null;
      if (depth == 0) {
        surfaces.add(boundaries.get(i));
        flatValues.add(value);
      } else {
        flattenSurfaces(
            boundaries.get(i), value == null ? values : value, depth - 1, surfaces, flatValues);
      }
    }
  }

  private static void addZs(JsonNode surface, List<Double> vertices, List<Double> zs) {
    for (var ring : surface) {
      for (var index : ring) {
        zs.add(vertices.get(index.asInt()));
      }
    }
  }

  /** Z of each vertex, with the CityJSON transform applied. */
  private static List<Double> toVertices(JsonNode cityJson) {
    var transform = cityJson.path("transform");
    var scaleZ = transform.path("scale").path(2).asDouble(1);
    var translateZ = transform.path("translate").path(2).asDouble(0);
    var zs = new ArrayList<Double>();
    for (var vertex : cityJson.path("vertices")) {
      zs.add(vertex.path(2).asDouble() * scaleZ + translateZ);
    }
    return zs;
  }

  private static double ceil2(double value) {
    return Math.ceil(value * 100) / 100;
  }
}
