package app.bpartners.geojobs.model.geometry;

import java.util.function.BiPredicate;
import lombok.AllArgsConstructor;

/*
 * Mostly generated by ChatGPT
 */
@AllArgsConstructor
public class HaveAnglesSameDirection implements BiPredicate<Double, Double> {

  private final double threshold;

  @Override
  public boolean test(Double angle1, Double angle2) {
    // Normalize the angles to the range [0, 2π)
    angle1 = normalizeAngle(angle1);
    angle2 = normalizeAngle(angle2);

    // Compute the absolute difference between the angles
    double diff = Math.abs(angle1 - angle2);

    // Adjust for wrap-around if the difference is greater than π
    diff = Math.min(diff, 2 * Math.PI - diff);

    // Check if the difference is within the threshold
    return diff <= threshold;
  }

  private static double normalizeAngle(double angle) {
    angle = angle % (2 * Math.PI); // Wrap angle to [-2π, 2π)
    if (angle < 0) {
      angle += 2 * Math.PI; // Convert negative angles to [0, 2π)
    }

    return angle;
  }
}
