openapi: 3.0.3
info:
  title: geo-tiler
  description: geo-tiler
  version: 'latest'
servers:
  - url: 'https://localhost:8080'
paths:
  '/ping':
    get:
      operationId: ping
      tags:
        - Health
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
  '/tilingJobs':
    post:
      operationId: tileZone
      description: creates a zone tiling job
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateZoneTilingJob"
      responses:
        200:
          description: the created zone tiling job
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ZoneTilingJob"
        '500':
          $ref: '#/components/responses/500'
    get:
      operationId: getTilingJobs
      description: gets a list of all tiling job
      parameters:
        - in: query
          name: page
          schema:
            $ref: "#/components/schemas/Page"
        - in: query
          name: pageSize
          schema:
            $ref: "#/components/schemas/PageSize"
      responses:
        200:
          description: all present jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ZoneTilingJob"
        '500':
          $ref: '#/components/responses/500'
components:
  responses:
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestException'
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotAuthorizedException'
    404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceNotFoundException'
    429:
      description: Too many requests to the API
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TooManyRequestsException'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerException'
  schemas:
    Exception:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    InternalServerException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: InternalServerException
        message: Unexpected error
    BadRequestException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: BadRequestException
        message: Bad request
    NotAuthorizedException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: NotAuthorizedException
        message: Not authorized
    ResourceNotFoundException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: ResourceNotFoundException
        message: Resource of type <T> identified by <I> not found
    TooManyRequestsException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: TooManyRequestsException
        message: Too many requests
    Page:
      type: integer
      description: Start at `1`
    PageSize:
      type: integer
      description: Cannot exceed `500`
    Feature:
      type: object
      properties:
        id:
          type: string
    CreateZoneTilingJob:
      type: object
      properties:
        emailReceiver:
          type: string
        zoneName:
          type: string
        features:
          type: array
          items:
            $ref: "#/components/schemas/Feature"
    ZoneTilingJob:
      allOf:
        - $ref: "#/components/schemas/CreateZoneTilingJob"
      properties:
        id:
          type: string