package app.bpartners.geojobs.repository.model.detection;

public enum DetectableType {
  TOITURE_REVETEMENT,
  PANNEAU_PHOTOVOLTAIQUE,
  PISCINE,
  PASSAGE_PIETON,
  ARBRE,
  TROTTOIR,
  LINE,
  ESPACE_VERT,
  VOIE_CARROSSABLE,
  PARKING,
  MOISISSURE,
  USURE,
  FISSURE_CASSURE,
  OBSTACLE,
  CHEMINEE,
  HUMIDITE,
  RISQUE_FEU
}
