AWSTemplateFormatVersion: 2010-09-09
Description: geo-jobs - Storage Postgres

Parameters:
  Env:
    Type: String
  DBName:
    Type: String
    Default: geo-jobs-rds
  ProdDbClusterTimeout:
    Type: Number

Conditions:
  IsProdEnv: !Equals
    - !Ref Env
    - 'prod'

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Join [ '', [ Subnet group for geo-jobs , !Ref Env ] ]
      DBSubnetGroupName: !Join [ '', [ geo-jobs-, !Ref Env, -subnet-group ] ]
      SubnetIds:
        - !Sub '{{resolve:ssm:/bpartners-imagery/private/subnet1/id}}'
        - !Sub '{{resolve:ssm:/bpartners-imagery/private/subnet2/id}}'

  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      BackupRetentionPeriod: 35
      DatabaseName: !Join [ '', !Split [ '-', !Ref DBName ] ]
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeletionProtection: true
      Engine: aurora-postgresql
      EngineMode: provisioned
      EngineVersion: 16.1
      MasterUsername: !Sub '{{resolve:ssm:/geo-jobs/${Env}/db/username}}'
      MasterUserPassword: !Sub '{{resolve:ssm:/geo-jobs/${Env}/db/password}}'
      VpcSecurityGroupIds:
        - !Sub '{{resolve:ssm:/bpartners-imagery/sg/id}}'
      ServerlessV2ScalingConfiguration:
        MaxCapacity: 64
        MinCapacity: 64

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DatabaseCluster
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup
    DependsOn: DatabaseCluster

  DatabaseClusterSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /geo-jobs/, !Ref Env, /db/url ] ]
      Type: String
      Value:
        Fn::Join:
          - ''
          - - jdbc:postgresql://
            - Fn::GetAtt:
                - DatabaseCluster
                - Endpoint.Address
            - ':'
            - Fn::GetAtt:
                - DatabaseCluster
                - Endpoint.Port
            - '/'
            - !Join [ '', !Split [ '-', !Ref DBName ] ]

  DatabaseClusterIdentifierSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /geo-jobs/, !Ref Env, /db/identifier ] ]
      Type: String
      Value: !GetAtt DatabaseCluster.Endpoint.Address

Outputs:
  DatabaseClusterSSM:
    Value: !GetAtt DatabaseClusterSSM.Value