package app.bpartners.geojobs.service.cityjson.exporter;

public enum CityJSONStep {
  POINT_EXTRACTION,
  RAW_PLANE_EXTRACTION,
  PLANE_CONTINUITY_EXTRACTION,
  CLOSED_PLANE_MERGING,
  RAW_DELIMITATION_EXTRACTION,
  DELIMITATION_SIMPLIFICATION
}
