on:
  push:
    branches:
      - '*'
    paths:
      - 'src/main/java/app/bpartners/geojobs/service/cityjson/texture/**'
      - 'src/test/java/app/bpartners/geojobs/service/cityjson/texture/**'
      - '.github/workflows/cityjson-texture-test.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - 'src/main/java/app/bpartners/geojobs/service/cityjson/texture/**'
      - 'src/test/java/app/bpartners/geojobs/service/cityjson/texture/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      AWS_REGION: eu-west-3

    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: chmod +x gradlew
      - run: ./gradlew test --tests "CityJsonTextureComputerTest"