name: Detection creation IT

on:
  schedule:
    - cron: '0 05 * * *'
    - cron: '0 06 * * *'
    - cron: '0 07 * * *'
    - cron: '0 08 * * *'
    - cron: '0 09 * * *'
    - cron: '0 10 * * *'
    - cron: '0 11 * * *'
    - cron: '0 12 * * *'
    - cron: '0 13 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch:

env:
  API_URL: ${{ secrets.DETECTION_API_URL }}
  API_KEY: ${{ secrets.DETECTION_API_KEY }}

jobs:
  detection-creation:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - name: Generate detection_e2_id and store inside file
        run: |
          detection_e2_id=$(uuidgen)
          echo "$detection_e2_id" > detection_e2_id.txt
          echo "detection_e2_id=$detection_e2_id" >> $GITHUB_ENV
          echo "Generated detection_e2_id: '$detection_e2_id'"

      - name: Cache detection_e2_id for next run
        uses: actions/cache@v4
        with:
          path: detection_e2_id.txt
          key: detection_e2_id-cache-${{ runner.os }}-${{ github.sha }}

      - name: Send POST /detections/* request
        run: |
          http_code=$(curl -s -w "%{http_code}" -X POST "$API_URL/detections/$detection_e2_id" \
          -H "Content-Type: application/json" \
          -H "x-api-key: $API_KEY" \
          --data "@.github/workflows/detection-request.json" \
          -o >(tee detection-response.json))
          
          echo "HTTP Response Code: $http_code"
          
          if [ "${http_code:-0}" -ne 200 ]; then
            echo "Response Body:"
              cat detection-response.json
            exit 1
          fi